# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'VastuKripa' do

end

target 'VastuKripaTests' do

end

platform :ios, ‘8.1’
pod 'PayPal-iOS-SDK'